# Generated by Django 5.0.6 on 2024-05-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo')),
                ('seo_keyword', models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo')),
                ('seo_alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('in_home', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo')),
                ('seo_keyword', models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo')),
                ('seo_alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('in_home', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sections', to='oneapp.blog')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_sections', to='oneapp.service')),
            ],
        ),
    ]
