# Generated by Django 5.0.6 on 2024-05-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0002_blog_description_az_blog_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogsection',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogsection',
            name='title_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogsection',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
