# Generated by Django 5.0.6 on 2024-05-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0003_blogsection_description_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='title_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
