# Generated by Django 5.0.6 on 2024-05-30 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0004_service_description_az_service_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo')),
                ('seo_keyword', models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo')),
                ('seo_alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo')),
                ('title', models.CharField(max_length=200)),
                ('title_az', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_az', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('in_home', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_az', models.CharField(max_length=500, null=True)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('description', models.TextField()),
                ('description_az', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_sections', to='oneapp.portfolio')),
            ],
        ),
    ]
