# Generated by Django 5.0.6 on 2024-05-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0005_portfolio_portfoliosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
