# Generated by Django 5.0.6 on 2024-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0007_testmonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmonial',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testmonial',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testmonial',
            name='title_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='testmonial',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
