# Generated by Django 5.0.6 on 2024-05-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0008_testmonial_description_az_testmonial_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmonial',
            name='field',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmonial',
            name='field_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='testmonial',
            name='field_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='testmonial',
            name='full_name',
            field=models.CharField(default='Ceo', max_length=300),
            preserve_default=False,
        ),
    ]
