# Generated by Django 5.0.6 on 2024-05-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0010_category_tag_blog_category_blog_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
