# Generated by Django 5.0.6 on 2024-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0011_category_title_az_category_title_en_tag_title_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_alt',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_alt',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_description',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo'),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo'),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_title',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
