# Generated by Django 5.0.6 on 2024-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0012_category_created_at_category_seo_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
