# Generated by Django 5.0.6 on 2024-06-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0013_service_icon_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesection',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
