# Generated by Django 5.0.6 on 2024-06-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0015_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='customer',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='timeline',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
