# Generated by Django 5.0.6 on 2024-06-07 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0016_portfolio_customer_portfolio_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='timeline',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('project', models.CharField(max_length=300)),
                ('timeline', models.CharField(blank=True, max_length=300, null=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='oneapp.portfolio')),
            ],
        ),
    ]
