# Generated by Django 5.0.6 on 2024-06-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0017_remove_portfolio_customer_remove_portfolio_timeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_az',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='project_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='project_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='timeline_az',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='timeline_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
