# Generated by Django 5.0.6 on 2024-06-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0018_customer_company_az_customer_company_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosection',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
