# Generated by Django 5.0.6 on 2024-06-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0020_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
